@Backend_HostAddress = http://localhost:5022

GET {{Backend_HostAddress}}/test/
Accept: application/json

###

GET {{Backend_HostAddress}}/brand/

###

POST {{Backend_HostAddress}}/brand/
Content-Type: application/json

{
  "name": "Contry Club"
}

###

PUT {{Backend_HostAddress}}/brand/4
Content-Type: application/json

{
  "name": "Contry Club editado"
}

###

DELETE {{Backend_HostAddress}}/brand/4

###

GET {{Backend_HostAddress}}/product/

###

GET {{Backend_HostAddress}}/product/2

###

POST {{Backend_HostAddress}}/product/
Content-Type: application/json

{
  "name": "Coca cola 20ml",
  "cost": 10,
  "price": 50,
  "active": true,
  "brandId": 1
}
###

PUT {{Backend_HostAddress}}/product/1
Content-Type: application/json

{
  "name": "Coca cola 20ml actualizada",
  "cost": 15,
  "price": 50,
  "active": true,
  "brandId": 1
}

###

DELETE {{Backend_HostAddress}}/product/1

###

POST {{Backend_HostAddress}}/sales
Content-Type: application/json

{
  "date": "2025-09-23T21:46:27",
  "details": 
  [
    {
      "productId": 2,
      "unitPrice": 50,
      "quantity": 4
    },
    {
      "productId": 3,
      "unitPrice": 40,
      "quantity": 3
    }
  ]
}

###

GET {{Backend_HostAddress}}/sales/

  ###

  
GET {{Backend_HostAddress}}/sales/2